version: '3.2'
services: 
  nginx:
    build: ./conf/nginx/
   
    ports: 
      - "80:80"
      - "443:443"
    volumes: 
      - ./www/:/var/www/html/:rw
      - ./conf/nginx/conf.d:/etc/nginx/conf.d/:ro
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx/:/var/log/nginx/:rw
    links:
      - php-fpm:php-fpm
    restart: always   
    

  php-fpm:
    build: ./conf/php/
    expose: 
      - "9000"
    volumes: 
      - ./www/:/var/www/html/:rw
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/php-fpm/:/var/log/php-fpm/:rw
    links: 
      - mysql:mysql
      - redis:redis
    restart: always
    command: php-fpm

  mysql:
    build: ./conf/mysql/
    ports:
      - "3306:3306"
    volumes: 
      - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
      - ./mysql/:/var/lib/mysql/:rw
      - ./log/mysql/:/var/log/mysql/:rw
    environment: 
      MYSQL_ROOT_PASSWORD: 123456
    restart: always
    

  redis:
    build: ./conf/redis/
    ports: 
      - "6379:6379"
    volumes: 
      - ./redis/:/data
    restart: always

  node:
    build: ./conf/node/
    ports:
      - "8001:8001"
    volumes:
      - ./www/:/var/www/html/:rw
    tty: true